services:
  - type: web
    name: community-backend
    env: node
    plan: free  # Change to 'starter' or higher for production
    rootDir: Community-Backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
