services:
  - type: web
    name: community-backend
    env: node
    plan: free  # Change to 'starter' or higher for production
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
